mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ... your other URL patterns ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),    
    path("mock_tests/", views.MockTestView.as_view(), name="start_mock_test"),
    path("mock_tests/<int:mock_test_id>", views.answer_mock_test, name="answer_mock_test"),
    path("mock_tests/<int:pk>/result/", views.MockTestResultView.as_view(), name="mock_test_result"),
    path("start-mock-test/", views.StartMockTestView.as_view(), name="start_mock_test"),
    path("mock_tests/tag/<slug:tag_slug>/", views.MockTestView.as_view(), name="mock_test_by_tag"),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from taggit.managers import TaggableManager

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    tags = TaggableManager()
    attachment = models.FileField(upload_to='attachments/', blank=True, null=True)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

    def randomise_choicegs(self):
        return self.choice_set.order_by('?')
    
    def attachment_link(self):
        if self.attachment:
            return format_html('<a href="{}" download>Download</a>', self.attachment.url)
        return "(No attachment)"
    attachment_link.short_description = "Attachment"


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    correct = models.BooleanField(default=0)

    def __str__(self):
        return self.choice_text
    
class MockTest(models.Model):
    questions = models.ManyToManyField(Question)
    choices = models.ManyToManyField(Choice)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.created_at)

    def max_score(self):
        return self.questions.all().count()

    def score(self):
        return self.choices.filter(correct=True).count()

    def randomise_questions(self):
        return self.questions.order_by('?')

polls/forms.py
from django import forms
from taggit.models import Tag

class TagSelectForm(forms.Form):
    tag = forms.ModelChoiceField(
        queryset=Tag.objects.all(),
        empty_label=None,
        label="Select Tag",
        initial=lambda: Tag.objects.filter(name__iexact="General Culture").first()
    )

polls/views.py
import random

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import View, generic

from .forms import TagSelectForm
from .models import Choice, Question, MockTest
from taggit.models import Tag

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "mock_tests"

    def get_queryset(self):
        """Return the previous mock tests"""
        return MockTest.objects.order_by("-created_at")
    
class MockTestView(View):
    template_name = "polls/mock_test.html"

    def get(self, request, *args, **kwargs):
        tag_slug = kwargs.get("tag_slug")
        if tag_slug:
            # Filter questions by tag
            questions = Question.objects.filter(tags__slug=tag_slug).distinct()
        else:
            questions = Question.objects.all()
        question_ids = questions.values_list('id', flat=True)
        if len(question_ids) < 5:
            mock_test_question_ids = list(question_ids)
        else:
            mock_test_question_ids = random.sample(list(question_ids), k=5)
        mock_questions = Question.objects.filter(id__in=mock_test_question_ids)
        mock_test = MockTest.objects.create()
        mock_test.questions.set(mock_questions)
        mock_test.save()

        context = {
            "mock_test": mock_test,
        }
        return render(request, self.template_name, context)
    

class MockTestResultView(generic.DetailView):
    model = MockTest
    context_object_name = "mock_test"
    template_name = "polls/mock_test_result.html"


def answer_mock_test(request, mock_test_id):
    mock_test = get_object_or_404(MockTest, pk=mock_test_id)
    mock_test_question_ids = mock_test.questions.all().values_list('id', flat=True)
    
    choices_ids = []
    for question_id in mock_test_question_ids:
        choices_ids.append(request.POST[str(question_id)])

    mock_choices = Choice.objects.filter(id__in=choices_ids)
    mock_test.choices.set(mock_choices)
    mock_test.save()

    return HttpResponseRedirect(reverse("polls:mock_test_result", args=(mock_test.id,)))

class StartMockTestView(View):
    template_name = "polls/start_mock_test.html"

    def get(self, request, *args, **kwargs):
        form = TagSelectForm()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        form = TagSelectForm(request.POST)
        if form.is_valid():
            tag = form.cleaned_data["tag"]
            # Redirect to a new URL with the tag slug
            return HttpResponseRedirect(reverse("polls:mock_test_by_tag", args=(tag.slug,)))
        return render(request, self.template_name, {"form": form})

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if mock_tests %}
  <ul>
  {% for mock_test in mock_tests %}
    <li><a href="{% url 'polls:mock_test_result' mock_test.id %}">{{mock_test}}</li>
  {% endfor %}
  </ul>
{% else %}
  <p>No Mock Tests are available.</p>
{% endif %}

<a href="{% url 'polls:start_mock_test' %}">Start a new mock test</a>

 

polls/templates/polls/mock_test.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}" />

{% if mock_test.id %}
<form action="{% url 'polls:answer_mock_test' mock_test.id %}" method="post">
  {% csrf_token %} {% for question in mock_test.randomise_questions %}
  <div class="question-section">
    <legend><h1>{{ question.question_text }}</h1></legend>

    <div class="tags-section">
      <h4>Tags:</h4>
      {% for tag in question.tags.all %}
      <span class="tag">{{ tag.name }}</span>
      {% endfor %}
    </div>

    <div class="choices-section">
      <h4>Options:</h4>
      {% for choice in question.randomise_choices %}
      <input
        type="radio"
        name="{{question.id}}"
        id="choice{{ forloop.counter }}"
        value="{{ choice.id }}"
      />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label
      ><br />
      {% endfor %}
    </div>
  </div>
  {% endfor %}
  <div class="submit-section">
    <input class="btn" type="submit" value="Answer" />
  </div>
</form>
{% endif %}

polls/templates/polls/mock_test_result.html
<h1>Result for the mock test created at {{ mock_test.created_at }}</h1>

<h3>Your score was {{ mock_test.score }} out of {{ mock_test.max_score }}.</h3>

<a href="{% url 'polls:index' %}">Return to home page.</a>

polls/templates/polls/start_mock_test.html
<h2>Start a New Mock Test</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Start Mock Test</button>
</form>